### ISSUE TITLE
希望可以出一个hexo版本

### ISSUE THREAD

**Issue by L1cardo** [luokangyuan/ghost-theme-mj#50]
希望可以出一个hexo版本

**Comment by luokangyuan** [comment]
[https://github.com/blinkfox/hexo-theme-matery](https://github.com/blinkfox/hexo-theme-matery)
这个`Hexo`主题是我和我同事大佬后来一起写的，

**Comment by L1cardo** [comment]
我现在用的就是matery主题，但是我特别喜欢你的星星背景图，可以在matery设置吗？

**Comment by luokangyuan** [comment]
现在不可以，既然你提出来了，那么过几天我加一个吧

**Comment by L1cardo** [comment]
非常感谢！
